default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: pingpong_development

test:
  <<: *default
  database: pingpong_test
